from django.urls import path

from activity.views import (
    ActivityDashboardView,
    ActivityCounterpartiesView,
    ActivityOverviewView,
    ActivityProfileView,
    ActivityReceiptsReversalsView,
    ActivityRulesThresholdsView,
    ActivitySimulatorView,
    ActivitySimulationSettingsView,
    ActivityTier1ReviewView,
    ActivityTier2SessionsView,
    ActivityTransactionsView,
    counterparties_api,
    create_payment_intent_api,
    overview_stats_api,
    payment_reverse_view,
    receipts_api,
    rules_thresholds_api,
    rules_thresholds_update_api,
    simulator_presets_api,
    simulator_batch_run_api,
    simulator_dynamic_generate_api,
    simulator_run_api,
    specter_vendor_detail_api,
    tier1_queue_api,
    tier1_swipe_action_api,
    tier2_sessions_api,
    tier2_attestation_api,
    tier2_session_api,
    transactions_api,
    transaction_detail_partial,
)

app_name = "activity"

urlpatterns = [
    path("", ActivityDashboardView.as_view(), name="dashboard"),
    path("overview/", ActivityOverviewView.as_view(), name="overview"),
    path("transactions/", ActivityTransactionsView.as_view(), name="transactions"),
    path("tier1-review/", ActivityTier1ReviewView.as_view(), name="tier1_review"),
    path("tier2-sessions/", ActivityTier2SessionsView.as_view(), name="tier2_sessions"),
    path("counterparties/", ActivityCounterpartiesView.as_view(), name="counterparties"),
    path("rules-thresholds/", ActivityRulesThresholdsView.as_view(), name="rules_thresholds"),
    path("receipts-reversals/", ActivityReceiptsReversalsView.as_view(), name="receipts_reversals"),
    path("simulator/", ActivitySimulatorView.as_view(), name="simulator"),
    path("simulation-settings/", ActivitySimulationSettingsView.as_view(), name="simulation_settings"),
    path("profile/", ActivityProfileView.as_view(), name="profile"),
    path("transactions/detail/", transaction_detail_partial, name="transaction_detail"),
    path("transactions/<str:transaction_id>/", transaction_detail_partial, name="transaction_detail_legacy"),
    path("payments/<int:payment_id>/reverse/", payment_reverse_view, name="payment_reverse"),
    path("api/overview/stats/", overview_stats_api, name="overview_stats"),
    path("api/transactions/", transactions_api, name="transactions_api"),
    path("api/payments/create/", create_payment_intent_api, name="create_payment"),
    path("api/tier1/queue/", tier1_queue_api, name="tier1_queue"),
    path("api/tier1/swipe/", tier1_swipe_action_api, name="tier1_swipe"),
    path("api/tier2/session/", tier2_session_api, name="tier2_session"),
    path("api/tier2/sessions/", tier2_sessions_api, name="tier2_sessions_api"),
    path("api/tier2/attestation/", tier2_attestation_api, name="tier2_attestation"),
    path("api/counterparties/", counterparties_api, name="counterparties_api"),
    path("api/rules-thresholds/", rules_thresholds_api, name="rules_thresholds_api"),
    path("api/rules-thresholds/update/", rules_thresholds_update_api, name="rules_thresholds_update_api"),
    path("api/receipts/", receipts_api, name="receipts_api"),
    path("api/simulator/presets/", simulator_presets_api, name="simulator_presets_api"),
    path("api/simulator/run/", simulator_run_api, name="simulator_run_api"),
    path("api/simulator/run-batch/", simulator_batch_run_api, name="simulator_batch_run_api"),
    path("api/simulator/generate-dynamic/", simulator_dynamic_generate_api, name="simulator_dynamic_generate_api"),
    path("api/vendors/specter/", specter_vendor_detail_api, name="specter_vendor"),
]
