[project]
name = "vouch"
version = "0.0.1"
description = "Source behind vouch.co"
readme = "../README.md"
requires-python = ">=3.14.2"
dependencies = [
    "anthropic>=0.52.2",
    "brotli>=1.2.0",
    "celery>=5.6.0",
    "django>=6.0",
    "django-allauth[socialaccount]>=65.13.1",
    "django-celery-results>=2.6.0",
    "django-compressor>=4.6.0",
    "django-cotton>=2.6.0",
    "django-countries>=8.2.0",
    "django-extensions>=4.1",
    "django-import-export>=4.3.14",
    "django-multiselectfield>=1.0.1",
    "django-nested-admin>=4.1.6",
    "django-prettyjson>=0.4.1",
    "django-ses>=4.5.0",
    "django-timezone-field>=7.2.1",
    "django-tz-detect>=0.5.0",
    "django-widget-tweaks>=1.5.0",
    "flower>=2.0.1",
    "gunicorn>=23.0.0",
    "ipython>=9.8.0",
    "notebook>=7.5.1",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "posthog>=7.4.1",
    "plaid-python>=36.1.0",
    "psycopg2-binary>=2.9.11",
    "pyup-django>=0.4.0",
    "redis>=7.1.0",
    "requests>=2.32.5",
    "sentry-sdk>=2.48.0",
    "tzdata>=2025.3",
    "uvicorn-worker>=0.4.0",
    "whitenoise>=6.11.0",
]

[dependency-groups]
dev = [
    "basedpyright>=1.36.1",
    "django-debug-toolbar>=6.1.0",
    "django-stubs>=5.2.8",
    "djlint>=1.36.4",
    "factory-boy>=3.3.3",
    "jupyter>=1.1.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.11.1",
    "ruff>=0.14.10",
    "shadcn-django>=0.23.0",
    "uv-upx>=0.4.2",
]

[tool.ruff]
extend-exclude = ["migrations"]
line-length = 120
src = ["src", ".", "**/apps"]

[tool.ruff.lint]
extend-select = [
    "B",   # Bugbear
    "W",   # Warnings
    "N",   # Refactoring
    "RUF", # Ruff
    "I",   # Import
    "TID", # Tidy Imports 
    "DJ",  # Django
    "YTT", # Typing https://pypi.org/project/flake8-2020/

]
ignore = ["RUF005", "RUF012"]

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.format]
indent-style = "space"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "vouch.settings"
python_files = "tests.py *_tests.py tests/*.py"

[tool.basedpyright]
typeCheckingMode = "standard"
venvPath = "."
venv = ".venv"
include = ["vouch"]
extraPaths = ["vouch/apps"]
exclude = ["**/migrations", "**/__pycache__", "**/settings.py"]
reportMissingImports = true
reportMissingTypeStubs = false
