name: Deployment to Production Server

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.ref_name }}

jobs:
  build-and-push-image:
    if: false # ******* Enable this when the production server is ready *******
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.TAG }},priority=100
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          target: backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=gha,mode=max,type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            UID=1000
            GID=1000
            DEBUG=false
            ENV=production

  terraform:
    if: false # ******* Enable this when the production server is ready *******
    name: Terraform
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    outputs:
      server_ip: ${{ steps.get_ip.outputs.ip }}
      private_key_pem: ${{ steps.get_private_key.outputs.private_key_pem }}
      certificate: ${{ steps.get_certificate.outputs.certificate }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: cd ops/prod/ && terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: cd ops/prod/ && terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: cd ops/prod/ && terraform plan -input=false

        # On push to "main", build or change infrastructure according to Terraform configuration files
        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        run: cd ops/prod/ && terraform apply -auto-approve -input=false

      - name: Get Droplet IP
        id: get_ip
        run: |
          server_ip=$(cd ops/prod/ &&terraform output -raw server_ip)
          echo "ip=$server_ip" >> $GITHUB_OUTPUT

      - name: Get Private Key
        id: get_private_key
        run: |
          private_key_pem=$(cd ops/prod/ &&terraform output -raw private_key_pem)
          pem_escaped=${private_key_pem//$'\n'/\\n}
          echo "private_key_pem=$pem_escaped" >> $GITHUB_OUTPUT

      - name: Get Certificate
        id: get_certificate
        run: |
          certificate=$(cd ops/prod/ &&terraform output -raw certificate)
          pem_escaped=${certificate//$'\n'/\\n}
          echo "certificate=$pem_escaped" >> $GITHUB_OUTPUT

  deploy:
    if: false # ******* Enable this when the production server is ready *******
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: [build-and-push-image, terraform]
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Add Certificates
        env:
          CG_PEM: ${{ needs.terraform.outputs.certificate }}
          CG_KEY: ${{ needs.terraform.outputs.private_key_pem }}
        run: |
          echo -e "$CG_PEM" > server_certificate.pem
          echo -e "$CG_KEY" > server_private.key

      - name: Add environment variables to .env
        run: |
          echo DOCKER_BUILDKIT=0 >> .env
          echo COMPOSE_DOCKER_CLI_BUILD=0 >> .env
          echo COMPOSE_PROFILES=postgres,redis,backend,worker,web >> .env
          echo DOCKER_RESTART_POLICY=unless-stopped >> .env
          echo DOCKER_WEB_HEALTHCHECK_TEST=/bin/true >> .env
          echo DOCKER_WEB_VOLUME=/home/public:/code/src/public >> .env
          echo ENVIRONMENT_NAME=production >> .env
          echo ENVIRONMENT_COLOR=#FF0000 >> .env
          echo DEBUG=false >> .env
          echo IS_STAGE=false >> .env
          echo IS_PROD=true >> .env
          echo TRACK_ANALYTICS=true >> .env
          echo SECRET_KEY=\"${{ secrets.SECRET_KEY }}\" >> .env
          echo SITE_URL="https://fusecup.co" >> .env
          echo ALLOWED_HOSTS="fusecup.co" >> .env
          echo TIME_ZONE="Europe/London" >> .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_DB=fusecup >> .env
          echo POSTGRES_USER=fusecup >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo EMAIL_BACKEND=django_ses.SESBackend >> .env
          echo "DEFAULT_FROM_EMAIL=\"fusecup <no-reply@mail.fusecup.co>\"" >> .env
          echo "SERVER_EMAIL=\"fusecup Server <no-reply-server@mail.fusecup.co>\"" >> .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo AWS_SES_REGION_NAME=us-east-1 >> .env
          echo AWS_SES_REGION_ENDPOINT=email.us-east-1.amazonaws.com >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }} >> .env
          echo POSTHOG_HOST=${{ vars.POSTHOG_HOST }} >> .env
          echo DJANGO_PROJECT_PATH="/code/src/" >> .env
          echo DOCKER_IMAGE_URL=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} >> .env
          echo DOCKER_IMAGE_TAG=${{ env.TAG }} >> .env
          echo DOCKER_FULL_IMAGE_URL=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} >> .env
          echo GITHUB_ACTOR=${{ github.actor }} >> .env
          echo GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" >> .env
          echo TURNSTILE_SITE_KEY=${{ secrets.TURNSTILE_SITE_KEY }} >> .env
          echo TURNSTILE_SECRET_KEY=${{ secrets.TURNSTILE_SECRET_KEY }} >> .env

      - name: Add private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"

      - name: Check Server IP
        env:
          SERVER_IP: ${{ needs.terraform.outputs.server_ip }}
        run: |
          echo $SERVER_IP

      - name: Print DOCKER_IMAGE_TAG
        env:
          TAG: ${{ env.TAG }}
        run: |
          echo $TAG

      - name: Print DOCKER_FULL_IMAGE_URL
        env:
          DOCKER_FULL_IMAGE_URL: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        run: |
          echo $DOCKER_FULL_IMAGE_URL

      - name: Build and deploy images on DigitalOcean
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SERVER_IP: ${{ needs.terraform.outputs.server_ip }}
        run: |
          sudo chmod -R 771 .
          sudo chmod -R 771 ./ops/prod/nginx/fusecup
          scp -o StrictHostKeyChecking=no -r ./.env ./docker-compose.yaml root@$SERVER_IP:/home/fusecup
          scp -o StrictHostKeyChecking=no -r ./ops/prod/nginx/fusecup root@$SERVER_IP:/etc/nginx/sites-available/
          scp -o StrictHostKeyChecking=no -r ./server_certificate.pem ./server_private.key root@$SERVER_IP:/etc/nginx/ssl/
          ssh -o StrictHostKeyChecking=no root@$SERVER_IP << 'ENDSSH'
            rm -rf /etc/nginx/sites-available/default
            rm -rf /etc/nginx/sites-enabled/default
            ln -s /etc/nginx/sites-available/fusecup /etc/nginx/sites-enabled/fusecup
            cd /home/fusecup
            source .env
            echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
            docker pull $DOCKER_FULL_IMAGE_URL
            docker compose up -d
            docker exec fusecup-backend-1 uv sync --frozen --no-dev
            docker exec -t fusecup-backend-1 python manage.py collectstatic --noinput
            docker exec -t fusecup-backend-1 python manage.py migrate
            sudo /etc/init.d/nginx restart
            docker image prune -a --force --filter "until=10h"
          ENDSSH
