name: Deployment to Stage Server

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: stage_v${{ github.run_number }}

jobs:
  deploy:
    if: false # ******* Enable this when the stage server is ready *******
    name: Deploy to GPie Stage Server
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Cloudflared
        env:
          SERVER_IP: ${{ secrets.SSH_SERVER_HOST }}
        run: |
          # Add cloudflare gpg key
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          # Add this repo to your apt repositories
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          # install cloudflared
          sudo apt-get update && sudo apt-get install cloudflared
          cloudflared access ssh-config --hostname local2.girishkumar.co --short-lived-cert

      - name: Add environment variables to .env
        run: |
          echo DOCKER_BUILDKIT=1 >> .env
          echo COMPOSE_DOCKER_CLI_BUILD=1 >> .env
          echo COMPOSE_PROFILES=postgres,redis,backend,worker,nginx >> .env
          echo DOCKER_RESTART_POLICY=unless-stopped >> .env
          echo DOCKER_WEB_HEALTHCHECK_TEST=/bin/true >> .env
          echo DOCKER_WEB_VOLUME=/home/gpi2/vouch/public:/code/src/public >> .env
          echo ENVIRONMENT_NAME=staging >> .env
          echo ENVIRONMENT_COLOR=#FFA500 >> .env
          echo DEBUG=false >> .env
          echo IS_STAGE=true >> .env
          echo IS_PROD=false >> .env
          echo TRACK_ANALYTICS=false >> .env
          echo SECRET_KEY=\"${{ secrets.SECRET_KEY }}\" >> .env
          echo SITE_URL="https://vouch.co" >> .env
          echo ALLOWED_HOSTS="vouch.co" >> .env
          echo TIME_ZONE="Europe/London" >> .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_DB=vouch >> .env
          echo POSTGRES_USER=vouch >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo EMAIL_BACKEND=django_ses.SESBackend >> .env
          echo "DEFAULT_FROM_EMAIL=\"vouch STAGE <no-reply@mail.vouch.co>\"" >> .env
          echo "SERVER_EMAIL=\"vouch Server STAGE <no-reply-server@mail.vouch.co>\"" >> .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo AWS_SES_REGION_NAME=us-east-1 >> .env
          echo AWS_SES_REGION_ENDPOINT=email.us-east-1.amazonaws.com >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }} >> .env
          echo POSTHOG_HOST=${{ vars.POSTHOG_HOST }} >> .env
          echo DOCKER_IMAGE_URL=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} >> .env
          echo DOCKER_IMAGE_TAG=${{ env.TAG }} >> .env
          echo DOCKER_FULL_IMAGE_URL=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} >> .env
          echo GITHUB_ACTOR=${{ github.actor }} >> .env
          echo GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" >> .env
          echo TURNSTILE_SITE_KEY=${{ secrets.TURNSTILE_SITE_KEY }} >> .env
          echo TURNSTILE_SECRET_KEY=${{ secrets.TURNSTILE_SECRET_KEY }} >> .env
        shell: bash

      - name: Add private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.GPI2_PRIVATE_KEY }}"
          echo "${{ secrets.CF_SSH_PUB }}" >> ~/.ssh/cf_ssh.pub
          echo "${{ secrets.GPI2_PRIVATE_KEY }}" >> ~/.ssh/id_vouch
          echo -e "\nHost *.girishkumar.co\n    ProxyCommand /usr/bin/cloudflared access ssh --hostname %h\n    CertificateFile  ~/.ssh/cf_ssh.pub" >> ~/.ssh/config

      - name: Check Server IP
        env:
          SERVER_IP: ${{ secrets.SSH_SERVER_HOST }}
        run: |
          echo $SERVER_IP

      - name: Print DOCKER_IMAGE_TAG
        env:
          TAG: ${{ env.TAG }}
        run: |
          echo $TAG

      - name: Print DOCKER_FULL_IMAGE_URL
        env:
          DOCKER_FULL_IMAGE_URL: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        run: |
          echo $DOCKER_FULL_IMAGE_URL

      - name: Build and deploy images on GPie Stage Server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SERVER_IP: ${{ secrets.SSH_SERVER_HOST }}
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_vouch -r ./.env gpi2@$SERVER_IP:/home/gpi2/vouch
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_vouch gpi2@$SERVER_IP << 'ENDSSH'
            cd /home/gpi2/vouch
            git pull --force
            source .env
            docker compose up -d --no-deps --build backend
            docker compose up -d
            docker exec -t ghostrez-backend-1 uv sync --frozen --no-dev
            docker exec -t vouch-backend-1 python manage.py collectstatic --noinput
            docker exec -t vouch-backend-1 python manage.py migrate
            docker image prune -a --force --filter "until=10h"
          ENDSSH
